<?php echo $this->header; ?>

	<div class="left">
		<div class="mapBox">
			<div class="map" id="map"><img src="/map/" alt="Server Map" /></div>
		</div>
		<div class="serverStats">
			<h2>Server Stats</h2>
			<div class="stat">Animals: <?php echo $this->serverProperties['spawn-animals'] ? 'Wandering' : 'Hiding'; ?></div>
			<div class="stat">Monsters: <?php echo $this->serverProperties['spawn-monsters'] ? 'Coming to get you' : 'Hiding'; ?></div>
			<div class="stat">Max Players: <?php echo $this->serverProperties['max-players']; ?></div>
		</div>
	</div>
	
	<div class="right">
		<div class="players">
			<h2>Players</h2>
			<?php /*
				foreach ($this->playerList as $player) { ?>
					<div class="player <?php echo $player->isOnline() ? 'online' : 'offline';?>">
						<a class="name"><?php echo $player->getUsername(); ?> <span class="status">(<?php echo $player->isOnline() ? 'online' : 'offline';?>)</span></a>
						<div class="info"></div>
					</div>
			<?php 
				}*/
			?>
		</div>
	</div>
	
	<div class="clear"></div>

<?php echo $this->footer; ?>