<?php echo $this->header; ?>

	<div class="left">
		<div class="mapBox">
		</div>
		<div class="serverStats">
			<h2>Server Stats</h2>
		</div>
	</div>
	
	<div class="right">
		<div class="players">
			<h2>Players</h2>
			<?php 
				foreach ($this->playerList as $player) { ?>
					<div class="player <?php echo $player->isOnline() ? 'online' : 'offline';?>">
						<a class="name"><?php echo $player->getUsername(); ?> <span class="status">(<?php echo $player->isOnline() ? 'online' : 'offline';?>)</span></a>
						<div class="info"></div>
					</div>
			<?php 
				}
			?>
		</div>
		<div class="chat">
			<h2>Chat</h2>
		</div>
	</div>
	
	<div class="clear"></div>

<?php echo $this->footer; ?>