<?php echo $this->header; ?>

	<div class="left">
		<div class="mapBox">
		</div>
		<div class="serverStats">
			<h2>Server Stats</h2>
		</div>
	</div>
	
	<div class="right">
		<div class="players">
			<ul>
				<?php 
					foreach ($this->playerList as $player) {
						echo '<li>' . $player->getUsername() . ' (' . ($player->isOnline() ? 'online' : 'offline'). ')</li>';
					}
				?>
			</ul>

			<h2>Players</h2>
			<div class="player online">
				<a class="name">Name <span class="status">(online)</span></a>
				<div class="info"></div>
			</div>
			
			<div class="player">
				<a class="name">Name <span class="status">(offline)</span></a>
				<div class="info"></div>
			</div>

		</div>
		<div class="chat">
			<h2>Chat</h2>
		</div>
	</div>
	
	<div class="clear"></div>

<?php echo $this->footer; ?>