<!doctype html>
<html lang="en-GB">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<title>Minecraft Monitor</title>
	<meta name="description" content="A Minecraft server monitoring web application" />
	<link rel="shortcut icon" href="/images/favicon.gif" type="image/gif" />

	<!-- Site CSS -->
	<link href="/css/default.css" rel="stylesheet" type="text/css" title="Default Theme" media="screen" />
</head>
<body id="body">
	<div class="pageContainer">
		<h1>MC Monitor</h1>
	</div>
</body>
</html>