<!doctype html>
<html lang="en-GB">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<title>Minecraft Monitor</title>
	<meta name="description" content="A Minecraft server monitoring web application" />
	<link rel="shortcut icon" href="/images/favicon.gif" type="image/gif" />

	<!-- Site CSS -->
	<link href="/css/default.css" rel="stylesheet" type="text/css" title="Default Theme" media="screen" />
	
	<!-- Fonts -->
	<link href='http://fonts.googleapis.com/css?family=VT323|Geo' rel='stylesheet' type='text/css'>
	
	<!-- JS Libs -->
	<script src="/js/libs/prototype.js" type="text/javascript"></script>
	<script src="/javascripts/scriptaculous.js" type="text/javascript"></script>
</head>
<body id="body">
	<div class="pageContainer">
		<div class="header">
			<div class="logo"></div>
			<div class="nav">
				<ul>
					<li><a href="http://www.minecraft.net/">Minecraft</a></li>
					<li><a href="http://www.minecraftwiki.net/">Minecraft Wiki</a></li>
					<li><a href="">Link</a></li>
				</ul>
			</div>
			<div class="bar"></div>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>