<?php echo $this->header; ?>

	<div class="errorPage">
		<h1>Fail! Something went wrong</h1>
		<h2>(<?php echo $this->message ?>)</h2>
		
		<div class="failPic"></div>

		<?php if (isset($this->exception)): ?>
  
		<h3>Exception information:</h3>
		<p>
			<b>Message:</b> <?php echo $this->exception->getMessage() ?>
		</p>

		<h3>Stack trace:</h3>
		<pre><?php echo $this->exception->getTraceAsString() ?>
		</pre>

		<h3>Request Parameters:</h3>
		<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
		</pre>

		<?php endif ?>
	</div>

<?php echo $this->footer; ?>